pi-tower-lamp:
  restart: always
  build: ./pi-tower-lamp
  privileged: true
  command: python main.py --mode rgbled
  volumes:
    - ./pi-tower-lamp:/usr/src/app/
  environment:
    - PYTHONUNBUFFERED=0